app.py
from flask import Flask

app = Flask(__name__)


@app.route('/')
def hello_world():
    return 'Hello World!'


if __name__ == '__main__':
    app.run()

apps/__init__.py
from flask import Flask
from settings import Development
from exts import db
from views.blog_view import blog_bp
from views.user_view import user_bp


def create_app():
    app = Flask(__name__,template_folder="../templates")
    app.config.from_object(Development)
    app.config["SECRET_KEY"] = "renyizifuchuan"
    db.init_app(app)
    #注册蓝图
    app.register_blueprint(blog_bp)
    app.register_blueprint(user_bp)
    return app

exts/__init__.py
from flask_sqlalchemy import SQLAlchemy
from flask import g,redirect
db = SQLAlchemy()

def check_login_wrapper(func):
    def check_login(*args,**kwargs):
        if not g.username:
            return redirect("/index")
        else:
            return func(*args, **kwargs)
    return check_login

views/blog_view.py
from flask import Blueprint,render_template,request,redirect,url_for,session,g
blog_bp = Blueprint('blog',__name__,url_prefix='/blog')
from model.blog_model import User
from exts import db
from exts import check_login_wrapper
@blog_bp.route("/")
def show_index():
    return render_template('index.html',childpage="index")


@blog_bp.route("/show_login")
def show_login():
        return render_template("login.html")


@blog_bp.route("/login",methods=["POST","GET"])
def login():
    if request.method == "POST":
        username = request.form.get("username")
        pwd = request.form.get("password")
        user = User.query.filter_by(username=username).first()
        if user:
            if pwd == user.userpassword:
                session["username"] = user.username
                g.username = session["username"]
                return render_template("index.html",childpage="index")
    else:
        return redirect("/blog/show_login")


@blog_bp.route("/register",endpoint='register',methods=['GET','POST'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        password1 = request.form.get('userpassword1')
        password2 = request.form.get('userpassword2')
        phonenumber = request.form.get('phonenumber')
        if password1 == password2:
            #注册进表
            user = User()
            user.username = username
            user.userpassword = password1
            user.phone = phonenumber
            db.session.add(user)
            db.session.commit()
            return '注册成功'
        else:
            return '重复确认密码不对'
    else:
        return render_template("register.html")


@blog_bp.route("/userall",endpoint="userall")
@check_login_wrapper
def userall():
    users = User.query.filter_by(isdelete=False).all()
    number = User.query.filter_by(isdelete=False).count()
    return render_template("userall.html",users=users,childpage="userall",number=number)


@blog_bp.route("/del/<int:userid>")
@check_login_wrapper
def deluser(userid):
    user = User.query.filter_by(userid=userid).first()
    user.isdelete = True
    db.session.commit()
    return redirect(url_for("blog.userall"))

@blog_bp.route("/show_update/<int:userid>",endpoint="show_update")
@check_login_wrapper
def show_update(userid):
    user = User.query.filter_by(userid=userid).first()
    return render_template("register.html",user=user)

views/user_view.py
from flask import blueprints,Blueprint,g,session,request

user_bp = Blueprint('user',__name__,url_prefix='/user')

# from manage import app
#
# @app.before_first_request
# def getsession():
#     if request.path == "/blog":
#         return None

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} 首页 {% endblock %}</title>
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <!-- 可选的 Bootstrap 主题文件（一般不用引入） -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css">
    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    {% block mycss %}  {% endblock %}
</head>
<body>
<div class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('blog.show_index') }}">myblog</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="{{ 'active' if childpage == 'index' else '' }}"><a href="{{ url_for('blog.show_index') }}">首页 </a></li>
            <li ><a href="#">发表</a></li>
            <li class="{{ 'active' if childpage == 'userall' else '' }}"><a href="{{url_for('blog.userall')}}">显示所有用户</a></li>
          </ul>
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">搜索用户</button>

          </form>
              <ul class="nav navbar-nav navbar-right">
            {% if not session['username'] %}
                <li><a href="{{ url_for('blog.show_login') }}">登陆</a></li>
                <li><a href="{{url_for('blog.register')}}">注册</a></li>
            {% else %}
                <li><a href="#">欢迎！{{ g.username }}</a> </li>
                <li><a href="{{ url_for("logout") }}">登出</a></li>
            {% endif %}
    </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    {% block content %}  {% endblock %}
{% block myjs %}  {% endblock %}
</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block loginstatus %}

{% endblock %}
{% block content %}
    <div>
        <span>index</span>
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %}

{% block content %}
    <form action="{{ url_for('blog.login') }}" method="post">
      <div class="form-group">
        <label for="username">Username</label>
        <input type="text" class="form-control" id="username" placeholder="Username" name="username">
      </div>
      <div class="form-group">
        <label for="exampleInputPassword2">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name="password">
      </div>
      <button type="submit" class="btn btn-default">登陆</button>
    </form>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block title %} Register {% endblock %}
{% block content %}
    <form action="{{ url_for('blog.register') }}" method="post">
      <div class="form-group">
        <label for="username">Username</label>
        <input type="text" class="form-control" id="username" placeholder="Username" name="username" value="{{ user.username if user else "" }}">
      </div>
      <div class="form-group">
        <label for="userpassword1">Password</label>
        <input type="password" class="form-control" id="userpassword1" placeholder="Password" name="userpassword1" value="{{ user.password if user else "" }}">
      </div>
      <div class="form-group">
        <label for="userpassword2">Password</label>
        <input type="password" class="form-control" id="userpassword2" placeholder="Please confirm Password" name="userpassword2" value="{{ user.password if user else "" }}">
      </div>
      <div class="form-group">
        <label for="phonenumber">Phonenumber</label>
        <input type="text" class="form-control" id="phonenumber" placeholder="Phonenumber" name="phonenumber" value="{{ user.phone if user else "" }}">
      </div>
      <button type="submit" class="btn btn-default">用户注册</button>
    </form>
{% endblock %}

templates/userall.html
{% extends 'base.html' %}
{% block content %}
    <table class="table table-hover">
        <tr>
            <th>编号</th>
            <th>用户名</th>
            <th>手机号</th>
            <th>注册日期</th>
            <th>操作</th>
        </tr>
    {% for user in users %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.phone }}</td>
            <td>{{ user.registdatetime }}</td>
            <td>
                <a class="btn btn-info" href="/blog/show_update/{{ user.userid }}" role="button">修改</a>
                <a class="btn btn-danger" href="/blog/del/{{ user.userid }}" role="button">删除</a>
            </td>
        </tr>
    {% endfor %}
    </table>

    <h3>共有{{ number }}条数据</h3>
{% endblock %}